---
version: '3'
services:
  cloudflared:
    image: cloudflare/cloudflared:2021.8.2
    hostname: cloudflared
    container_name: cloudflared
    command: "'tunnel' 'run' 'your_uuid_here'"
    networks:
      - proxy
    environment:
      - 'PGID=${ID}'
      - 'PUID=${ID}'
      - 'TZ=${TZ}'
    volumes:
      - /opt/appdata/cloudflared:/home/nonroot/.cloudflared
    restart: always
networks:
  proxy:
    driver: bridge
    external: true