---
version: '3'
services:
  muximux:
    hostname: 'muximux'
    container_name: 'muximux'
    environment:
      - 'PGID=${ID}'
      - 'PUID=${ID}'
      - 'TZ=${TZ}'
      - 'UMASK=${UMASK}'
    image: 'ghcr.io/linuxserver/muximux'
    restart: '${RESTARTAPP}'
    ports:
      - '${PORTBLOCK}:8015:80'
    networks:
      - proxy
    volumes:
      - '${APPFOLDER}/muximux:/config:rw'
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      - 'dockupdater.enable=true'
      - 'traefik.http.routers.muximux-rtr.entrypoints=https'
      - 'traefik.http.routers.muximux-rtr.rule=Host(`muximux.${DOMAIN}`)'
      - 'traefik.http.routers.muximux-rtr.tls=true'
      - 'traefik.http.routers.muximux-rtr.tls.certresolver=dns-cloudflare'
      - 'traefik.http.routers.muximux-rtr.middlewares=chain-authelia@file'
      - 'traefik.http.routers.muximux-rtr.service=muximux-svc'
      - 'traefik.http.services.muximux-svc.loadbalancer.server.port=80'
networks:
  proxy:
    driver: bridge
    external: true
