---
version: '3'
services:
  glances:
    hostname: 'glances'
    container_name: 'glances'
    image: 'nicolargo/glances:alpine-latest-full'
    restart: '${RESTARTAPP}'
    pid: host
    ports:
      - '${PORTBLOCK}:61208:61208'  
    environment:
      - 'TZ=${TZ}'
      - 'GLANCES_OPT=-w'
      - 'DOCKER_HOST=tcp://socket-proxy:2375'
    networks:
      - proxy
      - socket-proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      - 'dockupdater.enable=true'
      - 'traefik.http.routers.glances-rtr.entrypoints=https'
      - 'traefik.http.routers.glances.rule=Host(`glances.${DOMAIN}`)'
      - 'traefik.http.routers.glances-rtr.tls=true'
      - 'traefik.http.routers.glances-rtr.tls.certresolver=dns-cloudflare'
      - 'traefik.http.routers.glances-rtr.middlewares=chain-authelia@file'
      - 'traefik.http.routers.glances-rtr.service=glances-svc'
      - 'traefik.http.services.glances-svc.loadbalancer.server.port=61208'
networks:
  proxy:
    driver: bridge
    external: true
  socket-proxy:
    driver: bridge
    external: true