---
name: Run CLI
on:
  push:
    branches-ignore:
      - 'dependabot/**'
      - 'dev'
      - 'all-contributors/**'
  workflow_dispatch:

jobs:
  GHRC:
    if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/tags/*' }}
    name: Create Docker Image for wiki
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Prepare GHRC.io
        id: prep
        run: |
          DOCKER_IMAGE=ghcr.io/${GITHUB_REPOSITORY}
          VERSION=lastet
          if [[ $GITHUB_REF == refs/tags/* ]]; then
             VERSION=${GITHUB_REF#refs/tags/v}
          fi
          if [ "${{ github.event_name }}" = "dev" ]; then
             VERSION=nightly
          fi
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          if [[ $VERSION =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
             TAGS="$TAGS,${DOCKER_IMAGE}:latest"
          fi
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=title::${GITHUB_REPOSITORY}
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/amd64,linux/armhf,linux/arm64
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.6.0
      - name: Cache Docker layers
        uses: actions/cache@v2.1.6
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1.10.0 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push GHRC.io
        id: docker_build
        uses: docker/build-push-action@v2.7.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./wiki/Dockerfile
          platforms: linux/amd64,linux/armhf,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.prep.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache 
          labels: |
            org.opencontainers.image.title=${{ steps.prep.outputs.title }}
            org.opencontainers.image.version=${{ steps.prep.outputs.version }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  build:
    needs: GHRC
    name: Generate new tag
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: ChloePlanet/github-tag-action@2.0.3
        with:
          body: ${{steps.github_release.outputs.changelog}}
        env:
          GITHUB_TOKEN: ${{ secrets.CR_PAT }}
          WITH_V: true

  deploy:
    needs: [ GHRC , build ]
    name: Deploy Dockserver Wiki on GitHub Pages
    if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2.3.4
      - name: Set up Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.x
      - run: python3 -m pip install --upgrade pip
      - run: python3 -m pip install --upgrade --force-reinstall -r wiki/requirements.txt
      - run: mkdocs gh-deploy --force --config-file wiki/mkdocs.yml --remote-branch wiki

  discord:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs:
      - GHRC
      - deploy
    if: ${{ success() }}
    steps:
      - name: Notify
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.CR_PAT }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
          username: 'DockServer-Bot'
          avatar-url: 'https://octodex.github.com/images/Terracottocat_Single.png'
          title: 'DockServer-Bot: {{STATUS}}'
          description: 'DockServer-Bot trigged this {{STATUS}}!'
          include-details: 'true'
          color-success: '#4287f5'
          color-failure: 'eb4034'
          color-cancelled: '0x42daf5'
